[package]
name = "hello-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { version = "0.16.0", default-features = false, features = ["realloc"] }

[package.metadata.component]
target = { path = "../world.wit",  world = "runner" }

[package.metadata.component.dependencies]
