search-paths:
  - ./hello-runner/target/wasm32-wasi/release
  - ./hello-world/target/wasm32-wasi/release

instantiations:
  root:
    arguments:
      component:hello-wasm/hello@0.0.1:
        instance: helloworld
